# Generated by Django 5.0 on 2024-01-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100)),
                ('sobrenome', models.CharField(default='', max_length=100)),
                ('nascimento', models.DateField(default='2000-01-01')),
                ('altura', models.FloatField(default=0.0)),
                ('peso', models.FloatField(default=0.0)),
                ('pressao_arterial', models.CharField(default='', max_length=20)),
                ('glicemia', models.FloatField(default=0.0)),
                ('frequencia_cardiaca', models.IntegerField(default=0)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1)),
            ],
        ),
    ]
